nrf: Add NRFX_CTZ macro to fix nrf54l15 build
The nrfx GRTC driver requires NRFX_CTZ (count trailing zeros) macro
which was missing from the nrfx glue file. This caused a build error:
  error: implicit declaration of function 'NRFX_CTZ'

Added definition using GCC's __builtin_ctz() function.

Also fixed P2_PIN_NUM to use P2_PIN_NUM_SIZE for nRF54L15.